/**
 * Smoke test: build one PDF per template through the real export path (server
 * renderer → Chrome print), then report page count and extracted text, so layout
 * regressions are visible without opening a browser.
 *
 *   node scripts/smoke-pdf.mjs
 *
 * Add `--text` to dump the extracted text of every page.
 */
import { execFileSync } from 'node:child_process'
import { writeFile, mkdir, readFile } from 'node:fs/promises'
import { closeBrowser, htmlToPdf } from '../server/lib/chrome.js'
import { closeRenderer, renderInvoiceHtml } from '../server/lib/sheet-html.js'
import { amountInWords } from '../src/lib/words.js'

const base = {
  language: 'en-us',
  title: 'INVOICE',
  theme: 'blue',
  item_table_color: '000',
  company_name: 'Haputra',
  company_tagline: 'Branding & Website Design for SaaS, AI & B2B Growth',
  company_address_1: 'Jl. Contoh No. 1, Jakarta, Indonesia',
  company_address_2: 'NPWP 01.234.567.8-901.000',
  company_email: 'jonathan@haputra.com',
  company_phone: '+62 812 0000 0000',
  company_website: 'www.haputra.com',
  bill_to_label: 'Bill To',
  customer_name: 'Andrew — Railz',
  customer_attn: 'Attn: Andrew',
  customer_billing_address_1: 'Level 5, 100 Example Street',
  customer_billing_address_2: 'Sydney NSW 2000, Australia',
  customer_email: 'billing@railz.example',
  project_label: 'Project',
  project_title: 'Software Audit — Fleet Management Platform (Railz X Haputra)',
  project_description:
    'Scope: (a) verification of calculation engine accuracy; (b) independent data consistency checks; (c) system isolation & security testing (cross-council data protection); (d) architectural & developer-stability recommendations. Duration: 35 working days across 5 weeks — target completion 22–25 October 2026.',
  invoice_number_label: 'Invoice No.',
  invoice_number: 'INV/2026/09/001',
  invoice_date_label: 'Invoice Date',
  invoice_date: '2026-09-21',
  due_date_label: 'Due Date',
  due_date: '2026-10-05',
  payment_terms: 'Termin 1 — 30% down payment of total project value, invoiced at project kickoff.',
  item_table_header: {
    name: 'Description',
    milestone: 'Milestone',
    quantity: 'Qty',
    rate: 'Rate',
    tax1_name: 'Tax',
    amount: 'Amount',
  },
  line_items: [
    {
      name: 'Software audit engagement — first milestone (30% of total project value)',
      milestone: 'Termin 1 / 30%',
      quantity: '1',
      rate: '7500',
      tax1: '11',
    },
    { name: 'Stakeholder interview workshop', milestone: 'Discovery', quantity: '2', rate: '450', tax1: '11' },
  ],
  show_milestone: true,
  tax_label: 'VAT',
  show_tax_summary: true,
  currency_code: 'USD',
  currency_symbol: '$',
  sub_total_label: 'Subtotal',
  total_label: 'TOTAL DUE',
  amount_in_words_label: 'In words',
  show_amount_in_words: true,
  // filled in below from the same helper the UI uses, so the fixture can't drift
  amount_in_words: '',
  notes_label: 'Notes',
  payment_terms_label: 'Payment Terms',
  payment_details_label: 'Payment Details',
  terms_and_conditions_label: 'Terms & Conditions',
  bank_name: 'Bank Central Asia',
  bank_account_number: '1234567890',
  bank_account_name: 'Haputra Studio',
  bank_swift: 'CENAIDJA',
  bank_address: 'Jakarta, Indonesia',
  notes: 'Please use the invoice number above as the payment reference.',
  terms_and_conditions: 'Payment is due within 14 days of the invoice date.',
}

const dumpText = process.argv.includes('--text')

await mkdir('tmp/pdf', { recursive: true })
// a real logo exercises the embed path; the fixture is generated by
// scripts/make_logo_fixtures.py
const logoBytes = await readFile('scripts/fixtures/logo-240x80.png')
const logo = `data:image/png;base64,${logoBytes.toString('base64')}`

const subTotal = base.line_items.reduce((a, i) => a + Number(i.quantity) * Number(i.rate), 0)
const taxTotal = base.line_items.reduce((a, i) => a + (Number(i.quantity) * Number(i.rate) * Number(i.tax1)) / 100, 0)

for (const template_type of ['classic', 'standard', 'excel', 'compact']) {
  const payload = {
    ...base,
    template_type,
    logo,
    amount_in_words: amountInWords(subTotal + taxTotal, base.currency_code),
  }
  const bytes = await htmlToPdf(await renderInvoiceHtml(payload))
  const path = `tmp/pdf/invoice-${template_type}.pdf`
  await writeFile(path, bytes)
  const text = execFileSync('pdftotext', [path, '-'], { encoding: 'utf8' })
  const pages = (text.match(/\f/g) || []).length
  console.log(`${template_type}: ${bytes.byteLength} bytes, ${pages} page(s) -> ${path}`)
  if (dumpText) console.log(text.trim())
}

// a corrupt data URL must degrade to a logo-less invoice, never a 500
{
  const bytes = await htmlToPdf(await renderInvoiceHtml({ ...base, template_type: 'classic', logo: 'data:image/png;base64,not-an-image' }))
  await writeFile('tmp/pdf/invoice-bad-logo.pdf', bytes)
  console.log(`bad logo tolerated: ${bytes.byteLength} bytes -> tmp/pdf/invoice-bad-logo.pdf`)
}

await closeRenderer()
await closeBrowser()